name: Create Release and .deb Files Project

on: push

env:
  GNUTLS_CPUID_OVERRIDE: 0x1

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        set-safe-directory: true
    - uses: paulhatch/semantic-version@v5.4.0
      id: semantic_version
      with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-rc${increment}"
          #user_format_type: "csv"
          bump_each_commit: false
          search_commit_body: true
          #change_path: "."

    - name: 
      run: touch a
    # - name: Create production release
    #   uses: ncipollo/release-action@v1
    #   id: release
    #   with:
    #     tag: ${{ steps.tag_version.outputs.new_tag }}
    #     name: ${{ steps.semantic_version.outputs.version_tag }}
    #     body: changelog
    #     draft: false
    #     prerelease: false
    #     commit: ${{ steps.semantic_version.outputs.current_commit }}
    #     allowUpdates: false
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor