name: Create Release and .deb Files Project

on: push

env:
  GNUTLS_CPUID_OVERRIDE: 0x1

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        set-safe-directory: true
    - name: 
      run: touch a
    - name: Upload Release Assets
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: softprops/action-gh-release@v1
      with:
        files: 'a'

  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor