name: Create Release and .deb Files Project

on: push

env:
  GNUTLS_CPUID_OVERRIDE: 0x1

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        set-safe-directory: true
    - name: 
      run: touch a

  release:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: paulhatch/semantic-version@v5.4.0
        id: semantic_version
        with:
            tag_prefix: "v"
            major_pattern: "/!:|BREAKING CHANGE:/"
            # A string which indicates the flags used by the `major_pattern` regular expression. Supported flags: idgs
            major_regexp_flags: ""
            minor_pattern: "/feat(\\(.+\\))?:/"
            # A string which indicates the flags used by the `minor_pattern` regular expression. Supported flags: idgs
            minor_regexp_flags: ""
            version_format: "${major}.${minor}.${patch}-prerelease${increment}"
            user_format_type: "csv"
            bump_each_commit: false
            search_commit_body: true
            # enable_prerelease_mode: false
            #change_path: "."